name: flutter_image_sticker
description: Flutter image stickers give you the ability to edit other images on
  top of your background image.
version: 1.0.1
repository: https://github.com/the-ego/packages/flutter_image_sticker
# homepage:
environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.5.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
