name: flutter_image_sticker
description: A new Flutter project.
version: 1.0.0
repository: https://github.com/the-ego/packages/flutter_image_sticker
# homepage:

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
