name: image_editor
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  lottie: ^2.5.0
  google_fonts: ^5.1.0
  video_player: ^2.7.0
  image_picker: ^1.0.0
  flutter_drawing_board: ^0.5.0
  vibration: ^1.8.1
  render: ^0.1.3+1
  logger: ^2.0.1
  du_icons:
    git:
      url: https://github.com/the-ego/samples.git
      path: du_icons
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  

flutter:
  uses-material-design: true
