name: example
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  du_icons:
    git:
      url: https://github.com/the-ego/samples.git
      path: du_icons
  photo_card: 
    git:
      url: https://github.com/the-ego/packages.git
      path: photo_card
  video_player: ^2.7.0
  flutter_riverpod: ^2.4.4
  gal: ^1.8.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/stickers/
    - assets/backgrounds/
    - assets/frames/
    - assets/button.mp4

  fonts:
    - family: DUIcons
      fonts:
        - asset: assets/DIYIcons.ttf
