name: photo_card
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  du_icons:
    git:
      url: https://github.com/the-ego/samples.git
      path: du_icons
  flutter:
    sdk: flutter
  flutter_drawing_board: ^0.5.0
  flutter_svg: ^2.0.7
  image_picker: ^1.0.0
  lottie: ^2.5.0

  flutter_riverpod: ^2.4.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
